#[cfg(not(target_arch = "wasm32"))]
pub mod cache;
pub mod env;
pub mod hir;
pub mod resolve;
#[cfg(not(target_arch = "wasm32"))]
pub use cache::*;
pub use env::*;
pub use hir::*;
pub use resolve::*;
